default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: 'walter-white'
  password: '123456'


development:
  <<: *default
  database: resume_analyzer_development

test:
  <<: *default
  database: resume_analyzer_test

production:
  primary: &primary_production
    <<: *default
    database: resume_analyzer_production
    username: resume_analyzer
    password: <%= ENV["RESUME_ANALYZER_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: resume_analyzer_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: resume_analyzer_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: resume_analyzer_production_cable
    migrations_paths: db/cable_migrate
